version: "2"
services:
  app:
    container_name: compassionate_franklin_two
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo_bankrupty
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"